import { Router, type IRouter } from "express";
import branchesRouter from "./branches";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import levelsRouter from "./levels";
import studentsRouter from "./students";
import evaluationsRouter from "./evaluations";
import paymentsRouter from "./payments";
import expensesRouter from "./expenses";
import expenseTemplatesRouter from "./expense-templates";
import dashboardRouter from "./dashboard";
import observationsRouter from "./observations";
import groupsRouter from "./groups";
import earningsRouter from "./earnings";
import consultationsRouter from "./consultations";
import newsRouter from "./news";
import messagesRouter from "./messages";
import requestsRouter from "./requests";
import enrollmentRequestsRouter from "./enrollment-requests";
import storageRouter from "./storage";
import mediaRouter from "./media";
import settingsRouter from "./settings";
import attendanceRouter from "./attendance";
import confidenceMetricsRouter from "./confidenceMetrics";
import programsRouter from "./programs";
import adhocSessionsRouter from "./adhocSessions";
import staffPaymentRequestsRouter from "./staffPaymentRequests";
import customRolesRouter from "./customRoles";
import studioRouter from "./studio";
import ideasRouter from "./ideas";
import supportSessionsRouter from "./supportSessions";
import publicRouter from "./public";
import performanceReportsRouter from "./performanceReports";
import registrationRequestsRouter from "./registrationRequests";
import cmsRouter from "./cms";
import campaignsRouter from "./campaigns";
import aiRouter from "./ai";
import aiChatRouter from "./ai-chat";
import salariesRouter from "./salaries";
import scheduleRouter from "./schedule";
import notificationsRouter from "./notifications";

const router: IRouter = Router();

router.use(branchesRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(levelsRouter);
router.use(studentsRouter);
router.use(evaluationsRouter);
router.use(paymentsRouter);
router.use(expensesRouter);
router.use(expenseTemplatesRouter);
router.use(dashboardRouter);
router.use(observationsRouter);
router.use(groupsRouter);
router.use(earningsRouter);
router.use(consultationsRouter);
router.use(newsRouter);
router.use(messagesRouter);
router.use(requestsRouter);
router.use(enrollmentRequestsRouter);
router.use(storageRouter);
router.use(mediaRouter);
router.use(settingsRouter);
router.use(attendanceRouter);
router.use(confidenceMetricsRouter);
router.use(programsRouter);
router.use(adhocSessionsRouter);
router.use(staffPaymentRequestsRouter);
router.use(customRolesRouter);
router.use(studioRouter);
router.use(ideasRouter);
router.use(supportSessionsRouter);
router.use(publicRouter);
router.use(performanceReportsRouter);
router.use(registrationRequestsRouter);
router.use(cmsRouter);
router.use(campaignsRouter);
router.use(aiRouter);
router.use(aiChatRouter);
router.use(salariesRouter);
router.use(scheduleRouter);
router.use(notificationsRouter);

export default router;
