// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sidebar/SidebarCurrent.tsx": () => import("../components/mockups/sidebar/SidebarCurrent.tsx"),
  "./components/mockups/sidebar/SidebarNew.tsx": () => import("../components/mockups/sidebar/SidebarNew.tsx")
};
