import { table, text, id, timestamp, boolean } from "./helpers";

export const schoolSettingsTable = table("school_settings", {
  id: id(),
  schoolName: text("school_name").notNull().default("Kidspeak Language Center"),
  slogan: text("slogan").default("Where Progress Meets Precision."),
  sloganAr: text("slogan_ar").default("حيث يلتقي التقدم بالدقة."),
  registrationId: text("registration_id"),
  address: text("address"),
  phone: text("phone"),
  phone2: text("phone2"),
  email: text("email").default("contact@kidspeak.dz"),
  website: text("website"),
  instagram: text("instagram"),
  facebook: text("facebook"),
  youtube: text("youtube"),
  tiktok: text("tiktok"),
  logoUrl: text("logo_url"),
  logoWhiteUrl: text("logo_white_url"),
  logoPrintUrl: text("logo_print_url"),
  faviconUrl: text("favicon_url"),
  signatureUrl: text("signature_url"),
  invoiceFooterEn: text("invoice_footer_en").default("Thank you for trusting Kidspeak Language Center."),
  invoiceFooterAr: text("invoice_footer_ar").default("شكراً لثقتكم بمركز كيدسبيك للغات."),
  currency: text("currency").default("DZD"),
  currencySymbolAr: text("currency_symbol_ar").default("د.ج"),
  invoicePrefix: text("invoice_prefix").default("RCP-"),
  primaryColor: text("primary_color").default("#1B2E8F"),
  secondaryColor: text("secondary_color").default("#F5A600"),
  pupilLabel: text("pupil_label").default("Pupils"),
  pupilLabelAr: text("pupil_label_ar").default("تلاميذ"),
  welcomeAnnouncement: text("welcome_announcement"),
  workingDays: text("working_days"),
  workingHoursStart: text("working_hours_start"),
  workingHoursEnd: text("working_hours_end"),
  parentContactAdmin: boolean("parent_contact_admin").default(true),
  parentContactTeacher: boolean("parent_contact_teacher").default(true),
  parentContactPsychologist: boolean("parent_contact_psychologist").default(true),
  parentHideAdminName: boolean("parent_hide_admin_name").default(true),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export type SchoolSettings = typeof schoolSettingsTable.$inferSelect;
